//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Order
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Unit_name { get; set; }
        public Nullable<int> Unit_number { get; set; }
        public Nullable<int> Price { get; set; }
        public string Purches_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Order_Status { get; set; }
        public string Date { get; set; }
    }
}
