//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Application
    {
        public string Application_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string Marrage_status { get; set; }
        public string Last_degree { get; set; }
        public int Year { get; set; }
        public string Subject { get; set; }
        public string Post { get; set; }
        public string About { get; set; }
    }
}
