//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_with_Date
    {
        public int ID { get; set; }
        public int Order_Id { get; set; }
        public string Date { get; set; }
        public string User_Name { get; set; }
        public int Total_Price { get; set; }
        public Nullable<int> Selected { get; set; }
    }
}
