//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_With_Product
    {
        public int ID { get; set; }
        public int Package_Id { get; set; }
        public string Package_Name { get; set; }
        public int Product_Id { get; set; }
        public int Unit_Number { get; set; }
        public string Unit_Name { get; set; }
        public string Product_Name { get; set; }
        public string Photo { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
