//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Stock
    {
        public int Product_id { get; set; }
        public string Stock_unit { get; set; }
        public string Product_Name { get; set; }
    
        public virtual Product_Information Product_Information { get; set; }
    }
}
