//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Information
    {
        public int Product_id { get; set; }
        public string Product_name { get; set; }
        public string Unit { get; set; }
        public int Price_per_unit { get; set; }
        public string Tag { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<int> Special_Offer { get; set; }
    
        public virtual Product_Image Product_Image { get; set; }
        public virtual Product_Stock Product_Stock { get; set; }
        public virtual Image Image { get; set; }
    }
}
