//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special_Offer
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Unit { get; set; }
        public int Price_per_Unit { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTime> validity { get; set; }
    }
}
